language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mRWpoQa2HMBO97nXs/8bAZ4IdyIuPj8SO1lxbQ/O0hiUmEI6bEvETp0c0Z71G8WGmh9dpiEpafn+awdvcMkiSGaMEWXM7NgQlsrIPxAIgpDKJ/HVX0YZ8ff99nwY8Uq4GbdmG79dOL91gUw8xDjeG7VRHcwE+BY0FjKEkpf041PBn6wgz7cqzcmrldweQU0Ft8D8pCLoAjRMBZ1Fnp57iRHMv/wF+94tV9rjGtaXEQkdtINocdxl8y4mwXV86wGttpYcP6tHX6JxRrPoTCaZUWhMiXuRXjECg9ch+rku2ItWFOjk6GCWe8p2BNyriy9jrILjS72swQYOZTXWjwylRr5u5TxjhJ3VuZYjaI67jMVSICGgLGmMlzIu+tGh28VQ7P33NVNBa6lE1a1Wm4XhFZjVXcgrcx0Q+asuqnwUIW1q0pfWrFv0TgB8lpXIYyWjepVr6hQw4IGvCfVfZ5WKeOgsNvRfkIv79APcmj2DDuGbU28YjYsTWa9/vPKn2M8B8HXUCdd4eqJIO3trJgKCRJbldbyXlmQHWxcCJGhFqF/4yhWZlsGHTXZZYbIq0z3R4i4CpiY3WpQi65vcoSCWiOpndXutEIhqU46Ni6BUqLC0zuD2mzp5VK7VJoWp6UYSR5iUZByQho6ATrTfMP3u45/oSfNtu+ZV4mqOgaZekGo=
services:
- mongodb
